# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'Location consul instance'
    metrics_path: "/metrics"
    consul_sd_configs:
      # Please change to your local docker host
      #- server:  "docker.for.mac.localhost:8500"

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex: '.*prom-monitored.*'
      action: 'keep'
    - source_labels: ['__meta_consul_service']
      regex:         '(.*)'
      target_label:  'job'
      replacement:   '$1'
    - source_labels: ['__meta_consul_address','__meta_consul_service_port']
      regex:         '(.*);(.*)'
      target_label:  '__serviceaddress__'
      replacement:   '$1:$2'
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_dc']
      regex:         '(.*?)-(.*)'
      target_label:  'region'
      replacement:   '$2'
